[package]
name = "disk-inspector"
version = "0.0.1"
authors = ["Ray Britton <raybritton@gmail.com>"]
edition = "2018"

[dependencies]
sysinfo = "0.8.2"
chrono = "0.4.6"
cursive = "0.11.2"
simplelog = "0.5.3"
log = "0.4.6"